version: "3.8"
services:
  webserver:
    image: nginx:alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    restart: unless-stopped
    
  frontend:
    image: plone/plone-frontend:latest
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
      RAZZLE_API_PATH: http://localhost/++api++
    depends_on:
      - backend
    expose:
      - "3000"
    restart: unless-stopped
    
  backend:
    image: plone/plone-backend:6.1
    environment:
      SITE: Plone
      CORS_ALLOW_ORIGIN: "*"
    volumes:
      - data:/data
    expose:
      - "8080"
    restart: unless-stopped

volumes:
  data: {}